import { AdminShell } from "@/components/admin/AdminShell";
import { LocaleFields } from "@/components/admin/LocaleFields";
import { AdminImagePicker } from "@/components/admin/AdminImagePicker";
import { updateSiteAction } from "@/app/admin/actions";
import { prisma } from "@/lib/prisma";
import { siteBase, siteTranslations } from "@/lib/default-content";
import { locales } from "@/lib/i18n";

export const dynamic = "force-dynamic";

export default async function SettingsPage() {
  let site: any = { ...siteBase, translations: locales.map((locale) => ({ locale, ...siteTranslations[locale] })) };
  let databaseReady = Boolean(process.env.DATABASE_URL);
  if (databaseReady) try { site = await prisma.siteSetting.findUnique({ where: { id: "main" }, include: { translations: true } }) || site; } catch { databaseReady = false; }
  const translations = Object.fromEntries(locales.map((locale) => [locale, site.translations.find((item: any) => item.locale === locale) || siteTranslations[locale]]));
  return <AdminShell title="Thông tin website" description="Thay đổi thương hiệu, liên hệ, ảnh hero và toàn bộ nội dung bốn ngôn ngữ.">{!databaseReady && <div className="admin-alert warning">Database chưa kết nối. Form hiển thị dữ liệu mẫu nhưng chỉ lưu được sau khi MySQL sẵn sàng.</div>}<form action={updateSiteAction} className="admin-panel admin-form"><div className="admin-panel-heading"><div><h2>Thông tin chung</h2><p>Các trường dùng chung cho mọi ngôn ngữ.</p></div><button className="admin-primary-button" disabled={!databaseReady}>Lưu thay đổi</button></div><div className="admin-form-grid"><label><span>Tên thương hiệu</span><input name="siteName" required defaultValue={site.siteName} /></label><label><span>Giờ mở cửa</span><input name="openingHours" required defaultValue={site.openingHours} /></label><label><span>Hotline</span><input name="phone" required defaultValue={site.phone} /></label><label><span>Số Zalo</span><input name="zalo" required defaultValue={site.zalo} /></label><label><span>Email</span><input name="email" type="email" defaultValue={site.email || ""} /></label><label><span>Messenger URL</span><input name="messenger" type="url" defaultValue={site.messenger || ""} /></label><label className="admin-full"><span>Địa chỉ</span><input name="address" required defaultValue={site.address} /></label><label><span>Facebook</span><input name="facebook" type="url" defaultValue={site.facebook || ""} /></label><label><span>Instagram</span><input name="instagram" type="url" defaultValue={site.instagram || ""} /></label><label className="admin-full"><span>Google Maps URL</span><input name="mapUrl" type="url" defaultValue={site.mapUrl || ""} /></label><div className="admin-full"><input type="hidden" name="currentHeroImage" value={site.heroImage} /><AdminImagePicker currentImage={site.heroImage} alt="Ảnh hero" urlName="heroImageUrl" urlLabel="Ảnh hero hiện tại / URL mới" fileName="heroImageFile" fileLabel="Hoặc chọn ảnh hero mới từ máy tính (tối đa 8MB)" /></div><label className="admin-full admin-video-url"><span>Video nền Hero — URL R2 (tuỳ chọn)</span><input name="heroVideo" type="url" placeholder="https://...r2.dev/909-lumina/ten-video.mp4" defaultValue={site.heroVideo || ""} /><small>Video phát tắt tiếng và lặp lại; ảnh Hero ở trên dùng làm ảnh dự phòng khi video chưa tải.</small></label></div><div className="admin-panel-heading admin-subheading"><div><h2>Nội dung đa ngôn ngữ</h2><p>Mở từng ngôn ngữ để chỉnh SEO và nội dung trang chủ.</p></div></div><LocaleFields values={translations} /><div className="admin-form-footer"><button className="admin-primary-button" disabled={!databaseReady}>Lưu toàn bộ nội dung</button></div></form></AdminShell>;
}
