import type { Locale } from "@/lib/i18n";
import type { PublicPost } from "@/lib/content";

const publishedAt = "2026-08-15T00:00:00.000Z";

export function seoPosts(locale: Locale): PublicPost[] {
  if (locale !== "vi") return [];
  return [
    { id: "seo-lounge-garden-q5", slug: "lounge-san-vuon-quan-5", coverImage: "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1400&q=84", title: "Lounge sân vườn Quận 5: Chọn không gian cho một buổi tối trọn vẹn", excerpt: "Gợi ý những tiêu chí thực tế khi tìm một không gian lounge sân vườn để gặp gỡ, hẹn hò hoặc đi cùng nhóm bạn.", content: "Tìm một lounge sân vườn ở Quận 5 không chỉ là chọn một nơi có hình ảnh đẹp. Không gian cần đủ thoáng để nhóm bạn trò chuyện, đủ chỉn chu cho một cuộc hẹn, và có nhịp điệu phù hợp khi buổi tối dần sôi động hơn. Vì vậy, xem trước menu, không gian và thông tin sự kiện là bước chuẩn bị hữu ích trước khi lên kế hoạch.\n\n909 Lumina Garden Lounge tại 909 Trần Hưng Đạo, Phường Chợ Quán là điểm hẹn kết hợp cảm giác thư giãn của khu vực sân vườn với trải nghiệm lounge về đêm. Thiết kế không gian mở, ánh sáng và âm nhạc tạo nên bối cảnh phù hợp để gặp gỡ bạn bè, hẹn hò hoặc tổ chức một buổi sinh nhật thân mật.\n\nMột buổi tối trọn vẹn thường không cần lịch trình quá phức tạp: chọn thời điểm phù hợp, xem trước các lựa chọn cocktail và theo dõi tin tức để biết những hoạt động đang được công bố. Với nhóm đông người hoặc cuối tuần, chủ động đặt bàn giúp trải nghiệm thuận tiện hơn.\n\n909 Lumina hoạt động từ 16:00 đến 00:00. Bạn có thể xem menu và các nội dung sự kiện trên website trước khi ghé thăm, sau đó liên hệ trực tiếp để xác nhận chỗ ngồi theo nhu cầu của nhóm.", publishedAt, featured: false, metaTitle: "Lounge sân vườn Quận 5 | 909 Lumina Garden Lounge", metaDescription: "Gợi ý chọn lounge sân vườn tại Quận 5 cho cuộc hẹn, gặp gỡ bạn bè và buổi tối cuối tuần." },
    { id: "seo-nightlife-q5", slug: "dia-diem-di-choi-buoi-toi-quan-5", coverImage: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1400&q=84", title: "Địa điểm đi chơi buổi tối Quận 5: Lên kế hoạch cho cuộc hẹn và nhóm bạn", excerpt: "Một vài tiêu chí giúp chọn địa điểm đi chơi buổi tối phù hợp với cuộc hẹn, sinh nhật nhỏ hoặc buổi gặp cuối tuần.", content: "Một địa điểm đi chơi buổi tối phù hợp thường bắt đầu từ câu hỏi đơn giản: bạn muốn một cuộc trò chuyện yên tĩnh, một buổi hẹn, hay một đêm gặp gỡ đông người? Khi đã xác định được dịp gặp gỡ, bạn sẽ dễ chọn không gian, thời điểm và cách đặt bàn phù hợp hơn.\n\nỞ Quận 5, 909 Lumina Garden Lounge là một lựa chọn dành cho những buổi gặp gỡ có cocktail, âm nhạc và không khí giải trí về đêm. Không gian Garden Lounge tạo điều kiện để chuyển từ phần đầu buổi tối thư giãn sang những khoảnh khắc sôi động hơn theo hoạt động đang diễn ra.\n\nTrước khi đến, hãy xem menu để tham khảo đồ uống, đọc phần tin tức để theo dõi sự kiện và cân nhắc đặt bàn nếu đi vào cuối tuần hoặc theo nhóm. Cách chuẩn bị này đặc biệt hữu ích cho cuộc hẹn, sinh nhật nhỏ hoặc buổi tụ họp sau giờ làm.\n\n909 Lumina Garden Lounge tọa lạc tại 909 Trần Hưng Đạo, Phường Chợ Quán, TP. Hồ Chí Minh và hoạt động từ 16:00 đến 00:00. Thông tin trên website là nơi nên kiểm tra đầu tiên trước khi lên lịch ghé thăm.", publishedAt, featured: false, metaTitle: "Địa điểm đi chơi buổi tối Quận 5 | 909 Lumina", metaDescription: "Gợi ý lên kế hoạch đi chơi buổi tối tại Quận 5: không gian, cocktail, âm nhạc và cách đặt bàn trước." }
  ];
}
