import { AdminShell } from "@/components/admin/AdminShell";
import { deletePostAction, upsertPostAction } from "@/app/admin/actions";
import { prisma } from "@/lib/prisma";
import { localeInfo, locales } from "@/lib/i18n";
import { DeleteButton } from "@/components/admin/DeleteButton";
import { AdminImagePicker } from "@/components/admin/AdminImagePicker";

export const dynamic = "force-dynamic";
const trans = (rows: any[], locale: string, key: string) => rows.find((row) => row.locale === locale)?.[key] || "";

export default async function PostsAdminPage() { let posts: any[] = []; let ready = Boolean(process.env.DATABASE_URL); if (ready) try { posts = await prisma.post.findMany({ orderBy: { createdAt: "desc" }, include: { translations: true } }); } catch { ready = false; } return <AdminShell title="Tin tức & sự kiện" description="Viết bài và tối ưu metadata theo bốn ngôn ngữ.">{!ready && <div className="admin-alert warning">Cần kết nối MySQL để quản lý bài viết.</div>}<section className="admin-panel"><div className="admin-panel-heading"><div><h2>Bài viết</h2><p>{posts.length} bài trong hệ thống.</p></div></div><div className="admin-editor-list"><details className="admin-editor" open={!posts.length}><summary>+ Tạo bài viết mới</summary><PostForm /></details>{posts.map((post) => <details className="admin-editor" key={post.id}><summary>{trans(post.translations, "vi", "title") || post.slug}<span>{post.published ? "Đã đăng" : "Bản nháp"}</span></summary><PostForm post={post} /></details>)}</div></section></AdminShell>; }

function PostForm({ post }: { post?: any }) { return <form action={upsertPostAction} className="admin-editor-form"><input type="hidden" name="id" value={post?.id || ""} /><input type="hidden" name="currentCoverImage" value={post?.coverImage || ""} /><div className="admin-form-grid"><div className="admin-full"><AdminImagePicker currentImage={post?.coverImage} alt={trans(post?.translations || [], "vi", "title") || "Ảnh bìa"} urlName="coverImageUrl" urlLabel="URL ảnh bìa" fileName="coverImageFile" fileLabel="Hoặc chọn ảnh bìa mới từ máy tính" /></div><label><span>Slug URL</span><input name="slug" required defaultValue={post?.slug || ""} placeholder="ten-su-kien" /></label><label><span>Ngày đăng</span><input name="publishedAt" type="date" defaultValue={post?.publishedAt ? new Date(post.publishedAt).toISOString().slice(0, 10) : ""} /></label>{locales.map((locale) => <div className="admin-language-block admin-full" key={locale}><h4>{localeInfo[locale].label}</h4><div className="admin-form-grid"><label className="admin-full"><span>Tiêu đề bài</span><input name={`${locale}_title`} required defaultValue={trans(post?.translations || [], locale, "title")} /></label><label className="admin-full"><span>Mô tả ngắn</span><textarea name={`${locale}_excerpt`} rows={2} required defaultValue={trans(post?.translations || [], locale, "excerpt")} /></label><label className="admin-full"><span>Nội dung (tách đoạn bằng một dòng trống)</span><textarea name={`${locale}_content`} rows={8} required defaultValue={trans(post?.translations || [], locale, "content")} /></label><label><span>Meta title (tuỳ chọn)</span><input name={`${locale}_metaTitle`} defaultValue={trans(post?.translations || [], locale, "metaTitle")} /></label><label><span>Meta description</span><textarea name={`${locale}_metaDescription`} rows={2} defaultValue={trans(post?.translations || [], locale, "metaDescription")} /></label></div></div>)}<label className="admin-check"><input name="published" type="checkbox" defaultChecked={post?.published ?? false} /><span>Xuất bản</span></label><label className="admin-check"><input name="featured" type="checkbox" defaultChecked={post?.featured ?? false} /><span>Bài nổi bật</span></label></div><div className="admin-editor-actions"><button className="admin-primary-button">Lưu bài viết</button>{post && <DeleteButton action={deletePostAction} label="Xoá bài" />}</div></form>; }
